// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeNi1y8QjAGUmcKBtPawfVFEriUIhY0Cc',
    appId: '1:733050008401:web:d7513f2e4a6b7d86fa5970',
    messagingSenderId: '733050008401',
    projectId: 'recipe-app-26d16',
    authDomain: 'recipe-app-26d16.firebaseapp.com',
    storageBucket: 'recipe-app-26d16.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0_xc_BELr4VrGgqXF49YXWODp79KfnTM',
    appId: '1:733050008401:android:d9e22adaa31dd852fa5970',
    messagingSenderId: '733050008401',
    projectId: 'recipe-app-26d16',
    storageBucket: 'recipe-app-26d16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9dWlPrjBhu2itOHAeIXDY3dH1ODOG9vc',
    appId: '1:733050008401:ios:6ef7b4d5c27fbe0cfa5970',
    messagingSenderId: '733050008401',
    projectId: 'recipe-app-26d16',
    storageBucket: 'recipe-app-26d16.firebasestorage.app',
    iosBundleId: 'com.example.reciepeApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9dWlPrjBhu2itOHAeIXDY3dH1ODOG9vc',
    appId: '1:733050008401:ios:6ef7b4d5c27fbe0cfa5970',
    messagingSenderId: '733050008401',
    projectId: 'recipe-app-26d16',
    storageBucket: 'recipe-app-26d16.firebasestorage.app',
    iosBundleId: 'com.example.reciepeApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeNi1y8QjAGUmcKBtPawfVFEriUIhY0Cc',
    appId: '1:733050008401:web:6cb73cd6eb2ce46dfa5970',
    messagingSenderId: '733050008401',
    projectId: 'recipe-app-26d16',
    authDomain: 'recipe-app-26d16.firebaseapp.com',
    storageBucket: 'recipe-app-26d16.firebasestorage.app',
  );
}
